### ISSUE TITLE
Support the new native vector type

### ISSUE THREAD

**Issue by roji** [efcore/EFCore.SqlServer.VectorSearch#3]
Azure SQL now has a native vector type ([blog post](https://devblogs.microsoft.com/azure-sql/eap-for-vector-support-refresh-introducing-vector-type/); this plugin should be changed to support that.

/cc @yorek

**Comment by JasonHaley** [comment]
Any idea when this is going to be worked on?

**Comment by roji** [comment]
This is pretty high up on my list of things to do, I expect to do this in the next few weeks.

**Comment by JasonHaley** [comment]
Awesome! Looking forward to it.
