### ISSUE TITLE
Update the IsVector extension methods

### ISSUE THREAD

**Issue by marcominerva** [efcore/EFCore.SqlServer.VectorSearch#6]
Instead of marking the `IsVector` extension methods as `Obsolete`:

https://github.com/efcore/EFCore.SqlServer.VectorSearch/blob/b4c6c691a1e38e11b81d5921cccf42b231c8bbbc/EFCore.SqlServer.VectorSearch/Extensions/SqlServerVectorSearchPropertyBuilderExtensions.cs#L9-L15

What do you think about having something like this?

```csharp
public static class SqlServerVectorSearchPropertyBuilderExtensions
{
    public static PropertyBuilder IsVector(this PropertyBuilder propertyBuilder, int size = 1536)
        => propertyBuilder.HasColumnType($"vector({size})");

    public static PropertyBuilder<T> IsVector<T>(this PropertyBuilder<T> propertyBuilder, int size = 1536)
        => propertyBuilder.HasColumnType($"vector({size})");
}
```

In this way, we limit the changes in the existing code and make the configuration more straightforward.

If you think it could be a good idea, I can take care of the PR.

**Comment by marcominerva** [comment]
@roji I have made the PR with the suggested idea (https://github.com/efcore/EFCore.SqlServer.VectorSearch/pull/8). I hope it could be a good improvement for the library.

/cc @yorek

**Comment by roji** [comment]
> we limit the changes in the existing code

@marcominerva as everything here is preview anyway (both this plugin and the Azure SQL support), I don't think we should go out of our way to avoid breaking changes - it's fine for people to have to do a minor adjustment when upgrading (and the obsoletion message tells them exactly what to do).

> make the configuration more straightforward

There are many other cases where users are expected to just configure a column type. For example, if you want a string with a maximum length, you use `HasColumnType("nvarchar(50)")`, very similar to how with vectors you now do `HasColumnType("vector(1536)")`. I'm not sure why the vector type needs a special `IsVector()` configuration API whereas nvarchar doesn't (and nobody's ever complained)...

**Comment by marcominerva** [comment]
Thank you for your response. I have proposed to mantain the `IsVector` extension method because it was present in the first version, but I understand your point.

**Comment by roji** [comment]
OK, thanks for engaging in any case! I'll go ahead and close this as I think it's better to leave it as obsoleted, since the vector type was a private preview until recently, it's unlikely this will affect many people in any case.
